name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: AllInOneLauncher.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install .NET
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

#    # Restore the application to populate the obj folder with RuntimeIdentifiers
#    - name: Restore the application
#      run: dotnet restore
#      env:
#        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create Main App
      run: dotnet publish -c Release -o PatchLauncher "AllInOneLauncher\AllInOneLauncher.csproj" --runtime win-x64 --self-contained true /p:UseAppHost=true
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Upload Patch-2.22-Launcher\PatchLauncher folder
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PatchLauncher.zip
        path: PatchLauncher

    # Zip the build artifacts
    - name: Zip build artifacts
      run: |
        cd PatchLauncher
        7z a -tzip ${{ github.workspace }}\PatchLauncher.zip *

    # Create a new Github Release
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: release-${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    # Upload the build artifacts to the new Github Release
    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.run_number }}
        files: PatchLauncher.zip
        fail_on_unmatched_files: true
        name: Patch Launcher Files - ${{ github.run_number }}